#include "TCUDA_enum.h"

char* TCUDA_DataType_enum[] = {
	"TCUDA_DATA_TYPE_PARAM",
	"TCUDA_DATA_TYPE_CHOP",
	"TCUDA_DATA_TYPE_TOP",
	"TCUDA_DATA_TYPE_OBJ",
	"TCUDA_DATA_TYPE_STR"
};
char* TCUDA_ProjectionType_enum[] = {
	"TCUDA_PROJECTION_TYPE_ORTHO",
    "TCUDA_PROJECTION_TYPE_PERSPECTIVE"
};
char* TCUDA_ObjSubType_enum[] = {
	"TCUDA_OBJ_SUB_TYPE_CAMERA",
	"TCUDA_OBJ_SUB_TYPE_GEO"
};
char* TCUDA_DataFormat_enum[] = {
	"TCUDA_DATA_FORMAT_UNSIGNED_BYTE",
	"TCUDA_DATA_FORMAT_FLOAT"
};
char* TCUDA_ParamDataFormat_enum[] = {
	"TCUDA_PARAM_DATA_FORMAT_UNSIGNED_BYTE,"
	"TCUDA_PARAM_DATA_FORMAT_FLOAT",
	"TCUDA_PARAM_DATA_FORMAT_STRUCT"
};
char* TCUDA_DataLocation_enum[] = {
	"TCUDA_DATA_LOCATION_DEVICE",
	"TCUDA_DATA_LOCATION_HOST"
};
char* TCUDA_ChanOrder_enum[] = {
    "TCUDA_CHAN_BGRA",
	"TCUDA_CHAN_A"
};
char* TCUDA_OutputType_enum[] = {
	"TCUDA_OUTPUT_TOP"
};
char* TCUDA_PixelFormat_enum[] = {
	"TCUDA_PIXEL_FORMAT_RGBA8",
	"TCUDA_PIXEL_FORMAT_RGBA32"
};
char* TCUDA_ObjParamType_enum[] = {
	"TCUDA_OBJ_PARAM_TYPE_TRANSFORMS",
    "TCUDA_OBJ_PARAM_TYPE_PARAMETERS"
};
char* TCUDA_FogType_enum[] = {
	"TCUDA_FOG_TYPE_OFF",
	"TCUDA_FOG_TYPE_LINEAR",
	"TCUDA_FOG_TYPE_EXPONENTIAL",
	"TCUDA_FOG_TYPE_EXPONENTIAL_SQUARED"
};
char* TCUDA_MemType_enum[] = {
	"TCUDA_MEM_TYPE_LINEAR",
    "TCUDA_MEM_TYPE_ARRAY"
};